spring:
  datasource:
    url: ${IAM_DB_URL:jdbc:mysql://localhost:3306/iam?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC}
    username: ${IAM_DB_USERNAME:root}
    password: ${IAM_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
